
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

#数据库配置

spring:
  datasource:
    url: jdbc:mysql://host.tanhuiri.cn:3306/byteluv?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19991119+thr
    type: com.alibaba.druid.pool.DruidDataSource   #配置阿里巴巴的Druid数据源

mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl